version: '3'


dotenv: ['.env']

tasks:
  client:
    cmds:
      - go build -C ./client -o ../.bin/client .
      - ./.bin/client
  
  server:
    cmds:
      - go build -C ./server -o ../.bin/server .
      - ./.bin/server
